on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Plesk
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.PLESK_USER }}
          key: ${{ secrets.PLESK_SSH_KEY }}
          script: |
            cd /var/www/vhosts/charles-vandendriessche.fr/httpdocs
            git pull origin main
            npm install
            npm run build
            npm run start
